name: Build, Push, and Deploy ip-finder app to aks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/container-ip-finder:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/container-ip-finder:latest

  terraform-apply:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Extract Azure Credentials
      id: azure-creds
      run: |
        echo "::set-output name=subscription_id::$(echo '${{ env.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)"
        echo "::set-output name=client_id::$(echo '${{ env.AZURE_CREDENTIALS }}' | jq -r .clientId)"
        echo "::set-output name=client_secret::$(echo '${{ env.AZURE_CREDENTIALS }}' | jq -r .clientSecret)"
        echo "::set-output name=tenant_id::$(echo '${{ env.AZURE_CREDENTIALS }}' | jq -r .tenantId)"

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="storage_account_name=tfstate${{ github.run_id }}" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="resource_group_name=tfstate" \
          -backend-config="subscription_id=${{ steps.azure-creds.outputs.subscription_id }}" \
          -backend-config="client_id=${{ steps.azure-creds.outputs.client_id }}" \
          -backend-config="client_secret=${{ steps.azure-creds.outputs.client_secret }}" \
          -backend-config="tenant_id=${{ steps.azure-creds.outputs.tenant_id }}"

    - name: Terraform Plan
      run: |
       terraform plan -out=tfplan \
        -var="image=${{ env.DOCKERHUB_USERNAME }}/container-ip-finder:latest" \
        -var="subscription_id=${{ steps.azure-creds.outputs.subscription_id }}" \
        -var="client_id=${{ steps.azure-creds.outputs.client_id }}" \
        -var="client_secret=${{ steps.azure-creds.outputs.client_secret }}" \
        -var="tenant_id=${{ steps.azure-creds.outputs.tenant_id }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Update Kubernetes Deployment
      run: |
        az aks get-credentials --resource-group myAKSResourceGroup --name myAKSCluster
        kubectl set image deployment/example-deployment example=${{ env.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}